# GRAY - index 0 (Walls)
# RED - index 1 (Start point)
# GREEN - index 2 (End point)
mazes = {
    "Maze 1": [
        [
            {'row': 0, 'col': 0, 'color_index': 4}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 0}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 1},
            {'row': 1, 'col': 0, 'color_index': 4}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 0}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 4}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 4}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 4}, {'row': 2, 'col': 1, 'color_index': 4}, {'row': 2, 'col': 2, 'color_index': 2}, {'row': 2, 'col': 3, 'color_index': 0}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 0}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 0},
            {'row': 3, 'col': 0, 'color_index': 0}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 0}, {'row': 3, 'col': 3, 'color_index': 0}, {'row': 3, 'col': 4, 'color_index': 4}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 4}, {'row': 3, 'col': 7, 'color_index': 4}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 4}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 0}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 0}, {'row': 4, 'col': 6, 'color_index': 0}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 0},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 0}, {'row': 5, 'col': 2, 'color_index': 4}, {'row': 5, 'col': 3, 'color_index': 0}, {'row': 5, 'col': 4, 'color_index': 4}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 4}, {'row': 5, 'col': 7, 'color_index': 4}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 0},
            {'row': 6, 'col': 0, 'color_index': 4}, {'row': 6, 'col': 1, 'color_index': 0}, {'row': 6, 'col': 2, 'color_index': 4}, {'row': 6, 'col': 3, 'color_index': 0}, {'row': 6, 'col': 4, 'color_index': 0}, {'row': 6, 'col': 5, 'color_index': 0}, {'row': 6, 'col': 6, 'color_index': 0}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 0}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 4}, {'row': 7, 'col': 5, 'color_index': 4}, {'row': 7, 'col': 6, 'color_index': 4}, {'row': 7, 'col': 7, 'color_index': 4}, {'row': 7, 'col': 8, 'color_index': 4}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 4}, {'row': 8, 'col': 3, 'color_index': 0}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 0}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 0}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 4}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 4}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 4}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 4}
        ]
    ],
    "Maze 2": [
        [
            {'row': 0, 'col': 0, 'color_index': 2}, {'row': 0, 'col': 1, 'color_index': 0}, {'row': 0, 'col': 2, 'color_index': 0}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 4}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 4},
            {'row': 1, 'col': 0, 'color_index': 4}, {'row': 1, 'col': 1, 'color_index': 4}, {'row': 1, 'col': 2, 'color_index': 4}, {'row': 1, 'col': 3, 'color_index': 4}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 0}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 0}, {'row': 1, 'col': 9, 'color_index': 4},
            {'row': 2, 'col': 0, 'color_index': 4}, {'row': 2, 'col': 1, 'color_index': 0}, {'row': 2, 'col': 2, 'color_index': 0}, {'row': 2, 'col': 3, 'color_index': 0}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 4}, {'row': 2, 'col': 8, 'color_index': 0}, {'row': 2, 'col': 9, 'color_index': 4},
            {'row': 3, 'col': 0, 'color_index': 4}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 4}, {'row': 3, 'col': 3, 'color_index': 0}, {'row': 3, 'col': 4, 'color_index': 4}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 0}, {'row': 3, 'col': 7, 'color_index': 4}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 4},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 0}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 4}, {'row': 4, 'col': 6, 'color_index': 0}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 0}, {'row': 4, 'col': 9, 'color_index': 0},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 0}, {'row': 5, 'col': 2, 'color_index': 0}, {'row': 5, 'col': 3, 'color_index': 0}, {'row': 5, 'col': 4, 'color_index': 0}, {'row': 5, 'col': 5, 'color_index': 4}, {'row': 5, 'col': 6, 'color_index': 4}, {'row': 5, 'col': 7, 'color_index': 4}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 4},
            {'row': 6, 'col': 0, 'color_index': 4}, {'row': 6, 'col': 1, 'color_index': 4}, {'row': 6, 'col': 2, 'color_index': 4}, {'row': 6, 'col': 3, 'color_index': 4}, {'row': 6, 'col': 4, 'color_index': 0}, {'row': 6, 'col': 5, 'color_index': 4}, {'row': 6, 'col': 6, 'color_index': 0}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 0}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 0}, {'row': 7, 'col': 2, 'color_index': 0}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 0}, {'row': 7, 'col': 5, 'color_index': 4}, {'row': 7, 'col': 6, 'color_index': 4}, {'row': 7, 'col': 7, 'color_index': 4}, {'row': 7, 'col': 8, 'color_index': 0}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 0}, {'row': 8, 'col': 3, 'color_index': 0}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 4}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 4}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 4}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 4}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 0}, {'row': 9, 'col': 7, 'color_index': 0}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 1}
        ]
    ],
    "Maze 3": [
        [
            {'row': 0, 'col': 0, 'color_index': 2}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 0}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 4}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 4},
            {'row': 1, 'col': 0, 'color_index': 0}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 0}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 4}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 0}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 0}, {'row': 2, 'col': 1, 'color_index': 0}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 4}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 4}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 4},
            {'row': 3, 'col': 0, 'color_index': 4}, {'row': 3, 'col': 1, 'color_index': 4}, {'row': 3, 'col': 2, 'color_index': 4}, {'row': 3, 'col': 3, 'color_index': 0}, {'row': 3, 'col': 4, 'color_index': 0}, {'row': 3, 'col': 5, 'color_index': 4}, {'row': 3, 'col': 6, 'color_index': 0}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 4},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 0}, {'row': 4, 'col': 2, 'color_index': 0}, {'row': 4, 'col': 3, 'color_index': 0}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 4}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 0}, {'row': 4, 'col': 9, 'color_index': 4},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 0}, {'row': 5, 'col': 2, 'color_index': 4}, {'row': 5, 'col': 3, 'color_index': 4}, {'row': 5, 'col': 4, 'color_index': 4}, {'row': 5, 'col': 5, 'color_index': 1}, {'row': 5, 'col': 6, 'color_index': 4}, {'row': 5, 'col': 7, 'color_index': 4}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 4},
            {'row': 6, 'col': 0, 'color_index': 4}, {'row': 6, 'col': 1, 'color_index': 0}, {'row': 6, 'col': 2, 'color_index': 4}, {'row': 6, 'col': 3, 'color_index': 0}, {'row': 6, 'col': 4, 'color_index': 4}, {'row': 6, 'col': 5, 'color_index': 4}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 0}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 0}, {'row': 7, 'col': 4, 'color_index': 0}, {'row': 7, 'col': 5, 'color_index': 4}, {'row': 7, 'col': 6, 'color_index': 0}, {'row': 7, 'col': 7, 'color_index': 0}, {'row': 7, 'col': 8, 'color_index': 4}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 4}, {'row': 8, 'col': 2, 'color_index': 4}, {'row': 8, 'col': 3, 'color_index': 4}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 4}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 0}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 0}, {'row': 9, 'col': 1, 'color_index': 0}, {'row': 9, 'col': 2, 'color_index': 0}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 0}, {'row': 9, 'col': 7, 'color_index': 4}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 0}
        ]
    ],
    "Maze 4": [
        [
            {'row': 0, 'col': 0, 'color_index': 4}, {'row': 0, 'col': 1, 'color_index': 0}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 0}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 0}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 0}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 2},
            {'row': 1, 'col': 0, 'color_index': 4}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 4}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 4}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 4}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 4}, {'row': 2, 'col': 1, 'color_index': 0}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 0}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 0}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 0},
            {'row': 3, 'col': 0, 'color_index': 4}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 4}, {'row': 3, 'col': 3, 'color_index': 0}, {'row': 3, 'col': 4, 'color_index': 4}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 4}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 0}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 0}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 0}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 0},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 0}, {'row': 5, 'col': 2, 'color_index': 4}, {'row': 5, 'col': 3, 'color_index': 0}, {'row': 5, 'col': 4, 'color_index': 4}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 4}, {'row': 5, 'col': 7, 'color_index': 0}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 0},
            {'row': 6, 'col': 0, 'color_index': 4}, {'row': 6, 'col': 1, 'color_index': 0}, {'row': 6, 'col': 2, 'color_index': 4}, {'row': 6, 'col': 3, 'color_index': 0}, {'row': 6, 'col': 4, 'color_index': 4}, {'row': 6, 'col': 5, 'color_index': 0}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 0}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 0}, {'row': 7, 'col': 4, 'color_index': 4}, {'row': 7, 'col': 5, 'color_index': 0}, {'row': 7, 'col': 6, 'color_index': 4}, {'row': 7, 'col': 7, 'color_index': 0}, {'row': 7, 'col': 8, 'color_index': 4}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 4}, {'row': 8, 'col': 3, 'color_index': 0}, {'row': 8, 'col': 4, 'color_index': 4}, {'row': 8, 'col': 5, 'color_index': 0}, {'row': 8, 'col': 6, 'color_index': 4}, {'row': 8, 'col': 7, 'color_index': 0}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 1}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 4}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 4}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 0}
        ]
    ],
    "Maze 5": [
        [
            {'row': 0, 'col': 0, 'color_index': 4}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 0}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 0}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 2},
            {'row': 1, 'col': 0, 'color_index': 4}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 4}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 4}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 4}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 4}, {'row': 2, 'col': 1, 'color_index': 0}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 0}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 0}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 0},
            {'row': 3, 'col': 0, 'color_index': 4}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 0}, {'row': 3, 'col': 3, 'color_index': 0}, {'row': 3, 'col': 4, 'color_index': 4}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 4}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 4}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 0}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 4}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 0},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 0}, {'row': 5, 'col': 2, 'color_index': 0}, {'row': 5, 'col': 3, 'color_index': 0}, {'row': 5, 'col': 4, 'color_index': 0}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 0}, {'row': 5, 'col': 7, 'color_index': 0}, {'row': 5, 'col': 8, 'color_index': 0}, {'row': 5, 'col': 9, 'color_index': 0},
            {'row': 6, 'col': 0, 'color_index': 4}, {'row': 6, 'col': 1, 'color_index': 0}, {'row': 6, 'col': 2, 'color_index': 0}, {'row': 6, 'col': 3, 'color_index': 4}, {'row': 6, 'col': 4, 'color_index': 0}, {'row': 6, 'col': 5, 'color_index': 4}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 4}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 4},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 4}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 0}, {'row': 7, 'col': 5, 'color_index': 4}, {'row': 7, 'col': 6, 'color_index': 0}, {'row': 7, 'col': 7, 'color_index': 0}, {'row': 7, 'col': 8, 'color_index': 0}, {'row': 7, 'col': 9, 'color_index': 4},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 0}, {'row': 8, 'col': 3, 'color_index': 0}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 0}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 0}, {'row': 8, 'col': 8, 'color_index': 0}, {'row': 8, 'col': 9, 'color_index': 4},
            {'row': 9, 'col': 0, 'color_index': 1}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 4}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 4}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 4}
        ]
    ],
    "Maze 6": [
        [
            {'row': 0, 'col': 0, 'color_index': 0}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 1}, {'row': 0, 'col': 6, 'color_index': 0}, {'row': 0, 'col': 7, 'color_index': 4}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 4},
            {'row': 1, 'col': 0, 'color_index': 0}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 4}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 4}, {'row': 1, 'col': 6, 'color_index': 0}, {'row': 1, 'col': 7, 'color_index': 4}, {'row': 1, 'col': 8, 'color_index': 0}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 0}, {'row': 2, 'col': 1, 'color_index': 0}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 0}, {'row': 2, 'col': 4, 'color_index': 0}, {'row': 2, 'col': 5, 'color_index': 4}, {'row': 2, 'col': 6, 'color_index': 0}, {'row': 2, 'col': 7, 'color_index': 4}, {'row': 2, 'col': 8, 'color_index': 0}, {'row': 2, 'col': 9, 'color_index': 0},
            {'row': 3, 'col': 0, 'color_index': 0}, {'row': 3, 'col': 1, 'color_index': 4}, {'row': 3, 'col': 2, 'color_index': 4}, {'row': 3, 'col': 3, 'color_index': 4}, {'row': 3, 'col': 4, 'color_index': 0}, {'row': 3, 'col': 5, 'color_index': 4}, {'row': 3, 'col': 6, 'color_index': 4}, {'row': 3, 'col': 7, 'color_index': 4}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 0}, {'row': 4, 'col': 1, 'color_index': 4}, {'row': 4, 'col': 2, 'color_index': 0}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 0}, {'row': 4, 'col': 5, 'color_index': 0}, {'row': 4, 'col': 6, 'color_index': 0}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 0},
            {'row': 5, 'col': 0, 'color_index': 0}, {'row': 5, 'col': 1, 'color_index': 4}, {'row': 5, 'col': 2, 'color_index': 4}, {'row': 5, 'col': 3, 'color_index': 4}, {'row': 5, 'col': 4, 'color_index': 4}, {'row': 5, 'col': 5, 'color_index': 4}, {'row': 5, 'col': 6, 'color_index': 4}, {'row': 5, 'col': 7, 'color_index': 0}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 0},
            {'row': 6, 'col': 0, 'color_index': 0}, {'row': 6, 'col': 1, 'color_index': 4}, {'row': 6, 'col': 2, 'color_index': 0}, {'row': 6, 'col': 3, 'color_index': 0}, {'row': 6, 'col': 4, 'color_index': 0}, {'row': 6, 'col': 5, 'color_index': 0}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 0}, {'row': 7, 'col': 1, 'color_index': 4}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 4}, {'row': 7, 'col': 5, 'color_index': 0}, {'row': 7, 'col': 6, 'color_index': 4}, {'row': 7, 'col': 7, 'color_index': 0}, {'row': 7, 'col': 8, 'color_index': 0}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 0}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 0}, {'row': 8, 'col': 3, 'color_index': 4}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 0}, {'row': 8, 'col': 6, 'color_index': 4}, {'row': 8, 'col': 7, 'color_index': 4}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 0}, {'row': 9, 'col': 1, 'color_index': 0}, {'row': 9, 'col': 2, 'color_index': 0}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 2}, {'row': 9, 'col': 6, 'color_index': 0}, {'row': 9, 'col': 7, 'color_index': 0}, {'row': 9, 'col': 8, 'color_index': 0}, {'row': 9, 'col': 9, 'color_index': 0}
        ]
    ],
    "Maze 7": [
        [
            {'row': 0, 'col': 0, 'color_index': 0}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 0}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 0},
            {'row': 1, 'col': 0, 'color_index': 0}, {'row': 1, 'col': 1, 'color_index': 4}, {'row': 1, 'col': 2, 'color_index': 0}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 0}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 4}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 4}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 0}, {'row': 2, 'col': 1, 'color_index': 4}, {'row': 2, 'col': 2, 'color_index': 0}, {'row': 2, 'col': 3, 'color_index': 4}, {'row': 2, 'col': 4, 'color_index': 0}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 0}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 0},
            {'row': 3, 'col': 0, 'color_index': 0}, {'row': 3, 'col': 1, 'color_index': 4}, {'row': 3, 'col': 2, 'color_index': 0}, {'row': 3, 'col': 3, 'color_index': 4}, {'row': 3, 'col': 4, 'color_index': 0}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 4}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 1}, {'row': 4, 'col': 1, 'color_index': 4}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 4}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 2},
            {'row': 5, 'col': 0, 'color_index': 0}, {'row': 5, 'col': 1, 'color_index': 4}, {'row': 5, 'col': 2, 'color_index': 0}, {'row': 5, 'col': 3, 'color_index': 4}, {'row': 5, 'col': 4, 'color_index': 0}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 4}, {'row': 5, 'col': 7, 'color_index': 0}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 0},
            {'row': 6, 'col': 0, 'color_index': 0}, {'row': 6, 'col': 1, 'color_index': 4}, {'row': 6, 'col': 2, 'color_index': 0}, {'row': 6, 'col': 3, 'color_index': 4}, {'row': 6, 'col': 4, 'color_index': 0}, {'row': 6, 'col': 5, 'color_index': 0}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 0}, {'row': 7, 'col': 1, 'color_index': 4}, {'row': 7, 'col': 2, 'color_index': 0}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 0}, {'row': 7, 'col': 5, 'color_index': 0}, {'row': 7, 'col': 6, 'color_index': 4}, {'row': 7, 'col': 7, 'color_index': 0}, {'row': 7, 'col': 8, 'color_index': 4}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 0}, {'row': 8, 'col': 1, 'color_index': 4}, {'row': 8, 'col': 2, 'color_index': 0}, {'row': 8, 'col': 3, 'color_index': 4}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 0}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 0}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 0}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 0}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 4}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 0}
        ]
    ],
    "Maze 8": [
        [
            {'row': 0, 'col': 0, 'color_index': 4}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 0}, {'row': 0, 'col': 7, 'color_index': 4}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 4},
            {'row': 1, 'col': 0, 'color_index': 0}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 0}, {'row': 1, 'col': 3, 'color_index': 4}, {'row': 1, 'col': 4, 'color_index': 0}, {'row': 1, 'col': 5, 'color_index': 4}, {'row': 1, 'col': 6, 'color_index': 0}, {'row': 1, 'col': 7, 'color_index': 4}, {'row': 1, 'col': 8, 'color_index': 0}, {'row': 1, 'col': 9, 'color_index': 4},
            {'row': 2, 'col': 0, 'color_index': 4}, {'row': 2, 'col': 1, 'color_index': 4}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 4}, {'row': 2, 'col': 4, 'color_index': 0}, {'row': 2, 'col': 5, 'color_index': 4}, {'row': 2, 'col': 6, 'color_index': 0}, {'row': 2, 'col': 7, 'color_index': 4}, {'row': 2, 'col': 8, 'color_index': 0}, {'row': 2, 'col': 9, 'color_index': 4},
            {'row': 3, 'col': 0, 'color_index': 0}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 0}, {'row': 3, 'col': 3, 'color_index': 4}, {'row': 3, 'col': 4, 'color_index': 0}, {'row': 3, 'col': 5, 'color_index': 4}, {'row': 3, 'col': 6, 'color_index': 0}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 0}, {'row': 3, 'col': 9, 'color_index': 4},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 4}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 0}, {'row': 4, 'col': 5, 'color_index': 4}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 4}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 4},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 0}, {'row': 5, 'col': 2, 'color_index': 0}, {'row': 5, 'col': 3, 'color_index': 4}, {'row': 5, 'col': 4, 'color_index': 0}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 0}, {'row': 5, 'col': 7, 'color_index': 4}, {'row': 5, 'col': 8, 'color_index': 0}, {'row': 5, 'col': 9, 'color_index': 4},
            {'row': 6, 'col': 0, 'color_index': 0}, {'row': 6, 'col': 1, 'color_index': 0}, {'row': 6, 'col': 2, 'color_index': 0}, {'row': 6, 'col': 3, 'color_index': 4}, {'row': 6, 'col': 4, 'color_index': 4}, {'row': 6, 'col': 5, 'color_index': 4}, {'row': 6, 'col': 6, 'color_index': 0}, {'row': 6, 'col': 7, 'color_index': 4}, {'row': 6, 'col': 8, 'color_index': 0}, {'row': 6, 'col': 9, 'color_index': 4},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 4}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 0}, {'row': 7, 'col': 5, 'color_index': 0}, {'row': 7, 'col': 6, 'color_index': 0}, {'row': 7, 'col': 7, 'color_index': 0}, {'row': 7, 'col': 8, 'color_index': 0}, {'row': 7, 'col': 9, 'color_index': 4},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 0}, {'row': 8, 'col': 3, 'color_index': 0}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 0}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 0}, {'row': 8, 'col': 8, 'color_index': 0}, {'row': 8, 'col': 9, 'color_index': 4},
            {'row': 9, 'col': 0, 'color_index': 4}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 4}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 2}, {'row': 9, 'col': 8, 'color_index': 0}, {'row': 9, 'col': 9, 'color_index': 1}
        ]
    ],
    "Maze 9": [
        [
            {'row': 0, 'col': 0, 'color_index': 1}, {'row': 0, 'col': 1, 'color_index': 0}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 0}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 0},
            {'row': 1, 'col': 0, 'color_index': 4}, {'row': 1, 'col': 1, 'color_index': 4}, {'row': 1, 'col': 2, 'color_index': 0}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 4}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 4}, {'row': 1, 'col': 7, 'color_index': 4}, {'row': 1, 'col': 8, 'color_index': 4}, {'row': 1, 'col': 9, 'color_index': 0},
            {'row': 2, 'col': 0, 'color_index': 0}, {'row': 2, 'col': 1, 'color_index': 4}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 0}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 0}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 0}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 0},
            {'row': 3, 'col': 0, 'color_index': 0}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 4}, {'row': 3, 'col': 3, 'color_index': 4}, {'row': 3, 'col': 4, 'color_index': 4}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 4}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 4}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 0}, {'row': 4, 'col': 1, 'color_index': 4}, {'row': 4, 'col': 2, 'color_index': 0}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 0}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 0}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 0},
            {'row': 5, 'col': 0, 'color_index': 0}, {'row': 5, 'col': 1, 'color_index': 4}, {'row': 5, 'col': 2, 'color_index': 0}, {'row': 5, 'col': 3, 'color_index': 4}, {'row': 5, 'col': 4, 'color_index': 4}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 0}, {'row': 5, 'col': 7, 'color_index': 0}, {'row': 5, 'col': 8, 'color_index': 4}, {'row': 5, 'col': 9, 'color_index': 0},
            {'row': 6, 'col': 0, 'color_index': 0}, {'row': 6, 'col': 1, 'color_index': 4}, {'row': 6, 'col': 2, 'color_index': 0}, {'row': 6, 'col': 3, 'color_index': 4}, {'row': 6, 'col': 4, 'color_index': 0}, {'row': 6, 'col': 5, 'color_index': 4}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 0}, {'row': 6, 'col': 8, 'color_index': 4}, {'row': 6, 'col': 9, 'color_index': 0},
            {'row': 7, 'col': 0, 'color_index': 0}, {'row': 7, 'col': 1, 'color_index': 4}, {'row': 7, 'col': 2, 'color_index': 0}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 0}, {'row': 7, 'col': 5, 'color_index': 4}, {'row': 7, 'col': 6, 'color_index': 4}, {'row': 7, 'col': 7, 'color_index': 4}, {'row': 7, 'col': 8, 'color_index': 4}, {'row': 7, 'col': 9, 'color_index': 0},
            {'row': 8, 'col': 0, 'color_index': 0}, {'row': 8, 'col': 1, 'color_index': 4}, {'row': 8, 'col': 2, 'color_index': 4}, {'row': 8, 'col': 3, 'color_index': 4}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 4}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 4}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 0},
            {'row': 9, 'col': 0, 'color_index': 0}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 0}, {'row': 9, 'col': 3, 'color_index': 4}, {'row': 9, 'col': 4, 'color_index': 4}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 0}, {'row': 9, 'col': 8, 'color_index': 4}, {'row': 9, 'col': 9, 'color_index': 2}
        ]
    ],
    "Maze 10": [
        [
            {'row': 0, 'col': 0, 'color_index': 1}, {'row': 0, 'col': 1, 'color_index': 4}, {'row': 0, 'col': 2, 'color_index': 4}, {'row': 0, 'col': 3, 'color_index': 4}, {'row': 0, 'col': 4, 'color_index': 4}, {'row': 0, 'col': 5, 'color_index': 4}, {'row': 0, 'col': 6, 'color_index': 4}, {'row': 0, 'col': 7, 'color_index': 4}, {'row': 0, 'col': 8, 'color_index': 4}, {'row': 0, 'col': 9, 'color_index': 4},
            {'row': 1, 'col': 0, 'color_index': 4}, {'row': 1, 'col': 1, 'color_index': 0}, {'row': 1, 'col': 2, 'color_index': 0}, {'row': 1, 'col': 3, 'color_index': 0}, {'row': 1, 'col': 4, 'color_index': 0}, {'row': 1, 'col': 5, 'color_index': 0}, {'row': 1, 'col': 6, 'color_index': 0}, {'row': 1, 'col': 7, 'color_index': 0}, {'row': 1, 'col': 8, 'color_index': 0}, {'row': 1, 'col': 9, 'color_index': 4},
            {'row': 2, 'col': 0, 'color_index': 4}, {'row': 2, 'col': 1, 'color_index': 0}, {'row': 2, 'col': 2, 'color_index': 4}, {'row': 2, 'col': 3, 'color_index': 4}, {'row': 2, 'col': 4, 'color_index': 4}, {'row': 2, 'col': 5, 'color_index': 4}, {'row': 2, 'col': 6, 'color_index': 4}, {'row': 2, 'col': 7, 'color_index': 4}, {'row': 2, 'col': 8, 'color_index': 4}, {'row': 2, 'col': 9, 'color_index': 4},
            {'row': 3, 'col': 0, 'color_index': 4}, {'row': 3, 'col': 1, 'color_index': 0}, {'row': 3, 'col': 2, 'color_index': 4}, {'row': 3, 'col': 3, 'color_index': 0}, {'row': 3, 'col': 4, 'color_index': 0}, {'row': 3, 'col': 5, 'color_index': 0}, {'row': 3, 'col': 6, 'color_index': 0}, {'row': 3, 'col': 7, 'color_index': 0}, {'row': 3, 'col': 8, 'color_index': 0}, {'row': 3, 'col': 9, 'color_index': 0},
            {'row': 4, 'col': 0, 'color_index': 4}, {'row': 4, 'col': 1, 'color_index': 0}, {'row': 4, 'col': 2, 'color_index': 4}, {'row': 4, 'col': 3, 'color_index': 4}, {'row': 4, 'col': 4, 'color_index': 4}, {'row': 4, 'col': 5, 'color_index': 4}, {'row': 4, 'col': 6, 'color_index': 4}, {'row': 4, 'col': 7, 'color_index': 4}, {'row': 4, 'col': 8, 'color_index': 4}, {'row': 4, 'col': 9, 'color_index': 4},
            {'row': 5, 'col': 0, 'color_index': 4}, {'row': 5, 'col': 1, 'color_index': 4}, {'row': 5, 'col': 2, 'color_index': 4}, {'row': 5, 'col': 3, 'color_index': 0}, {'row': 5, 'col': 4, 'color_index': 0}, {'row': 5, 'col': 5, 'color_index': 0}, {'row': 5, 'col': 6, 'color_index': 0}, {'row': 5, 'col': 7, 'color_index': 0}, {'row': 5, 'col': 8, 'color_index': 0}, {'row': 5, 'col': 9, 'color_index': 4},
            {'row': 6, 'col': 0, 'color_index': 0}, {'row': 6, 'col': 1, 'color_index': 0}, {'row': 6, 'col': 2, 'color_index': 0}, {'row': 6, 'col': 3, 'color_index': 0}, {'row': 6, 'col': 4, 'color_index': 4}, {'row': 6, 'col': 5, 'color_index': 4}, {'row': 6, 'col': 6, 'color_index': 4}, {'row': 6, 'col': 7, 'color_index': 4}, {'row': 6, 'col': 8, 'color_index': 0}, {'row': 6, 'col': 9, 'color_index': 4},
            {'row': 7, 'col': 0, 'color_index': 4}, {'row': 7, 'col': 1, 'color_index': 4}, {'row': 7, 'col': 2, 'color_index': 4}, {'row': 7, 'col': 3, 'color_index': 4}, {'row': 7, 'col': 4, 'color_index': 4}, {'row': 7, 'col': 5, 'color_index': 0}, {'row': 7, 'col': 6, 'color_index': 0}, {'row': 7, 'col': 7, 'color_index': 4}, {'row': 7, 'col': 8, 'color_index': 0}, {'row': 7, 'col': 9, 'color_index': 4},
            {'row': 8, 'col': 0, 'color_index': 4}, {'row': 8, 'col': 1, 'color_index': 0}, {'row': 8, 'col': 2, 'color_index': 0}, {'row': 8, 'col': 3, 'color_index': 0}, {'row': 8, 'col': 4, 'color_index': 0}, {'row': 8, 'col': 5, 'color_index': 4}, {'row': 8, 'col': 6, 'color_index': 0}, {'row': 8, 'col': 7, 'color_index': 4}, {'row': 8, 'col': 8, 'color_index': 4}, {'row': 8, 'col': 9, 'color_index': 4},
            {'row': 9, 'col': 0, 'color_index': 4}, {'row': 9, 'col': 1, 'color_index': 4}, {'row': 9, 'col': 2, 'color_index': 4}, {'row': 9, 'col': 3, 'color_index': 2}, {'row': 9, 'col': 4, 'color_index': 0}, {'row': 9, 'col': 5, 'color_index': 4}, {'row': 9, 'col': 6, 'color_index': 4}, {'row': 9, 'col': 7, 'color_index': 4}, {'row': 9, 'col': 8, 'color_index': 0}, {'row': 9, 'col': 9, 'color_index': 4}
        ]
    ]
}
